### ISSUE TITLE
Remove the dot from the registration name

### ISSUE THREAD

**Issue by shanielh** [aweber/rabbitmq-autocluster-consul#11]
First of all, This is a great project, Thank you very much for this great piece of software.

As you can see here : https://github.com/hashicorp/consul/issues/215 - Consul won't resolve services with "." in their names.

Because of this, The default name of the cluster service `rabbitmq.autocluster` should be changed to something more like `rabbitmq-autocluster`

**Comment by gmr** [comment]
Thanks! 0.3 is going to drop today or tomorrow that makes this optional.

**Comment by shanielh** [comment]
Thanks mate.

**Comment by gmr** [comment]
0.3.1 is out with this addressed. Thanks for raising the issue.
