### ISSUE TITLE
RabbitMQ 3.5.0 based release?

### ISSUE THREAD

**Issue by cap10morgan** [aweber/rabbitmq-autocluster-consul#2]
Should this be rebuilt against RabbitMQ 3.5.0 and another release made? Or has not enough changed to warrant it?

**Comment by gmr** [comment]
I just went through the process to build and test against 3.5.0 and it worked just fine. I expect the existing build will work as well, but I've yet to test that. I'll be changing a few things in the README and in the Vagrant/Docker setup for testing/building and then I'll double check that the plugin works fine with 3.4.x or 3.5.x in addition to 3.3.x. Thanks for the interest and I'd love to hear how it works for you.

**Comment by gmr** [comment]
I just tested the existing 0.1.0 binary against 3.5.0 and it worked as expected. I've updated the release notes and changed it so that downloading is now done via GitHub releases.  Cheers!
