### ISSUE TITLE
enabling the plugin succeeds but creating the services fails

### ISSUE THREAD

**Issue by schmitch** [aweber/rabbitmq-autocluster-consul#3]
Hello, currently I try to enable the plugin with:
```rabbitmq-plugins enable rabbitmq_autocluster_consul```

and get the following errors:

    The following plugins have been enabled:
      rabbitmq_autocluster_consul

    Applying plugin configuration to rabbit@rabbit1...
                  Consul Cluster Initializing: Cluster name: <<"envisia">>
    Query Body: "{\"Name\":\"rabbitmq:autocluster\", \"Tags\": [\"envisia\"]}"
    Cluster name: <<"envisia">>
    Error registering: {error,
                           {failed_connect,
                               [{to_address,{"127.0.0.1",8500}},
                                {inet,[inet],eacces}]}}
    Cluster name: <<"envisia">>
    Query URL: "http://127.0.0.1:8500/v1/catalog/service/rabbitmq:autocluster?tag=envisia"
    Cluster name: <<"envisia">>
    get_nodes response: {error,
                            {failed_connect,
                                [{to_address,{"127.0.0.1",8500}},
                                 {inet,[inet],eacces}]}}
                  First cluster node, no action.

     started 1 plugin.

consul is up and running, see:

    [root@rabbit1 ~]# consul members
    Node                      Address              Status  Type    Build  Protocol
    rabbit3.node.dc01.consul  192.168.32.24:8301   alive   client  0.5.0  2
    consul1                   192.168.32.203:8301  alive   server  0.5.0  2
    web2.node.dc01.consul     192.168.32.22:8301   alive   client  0.5.0  2
    consul3                   192.168.32.205:8301  alive   server  0.5.0  2
    rabbit2.node.dc01.consul  192.168.32.25:8301   alive   client  0.5.0  2
    web1.node.dc01.consul     192.168.32.21:8301   alive   client  0.5.0  2
    rabbit1.node.dc01.consul  192.168.32.26:8301   alive   client  0.5.0  2
    consul2                   192.168.32.204:8301  alive   server  0.5.0  2
    [root@rabbit1 ~]# netstat -ntap
    Aktive Internetverbindungen (Server und stehende Verbindungen)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      18055/beam.smp      
    tcp        0      0 127.0.0.1:8400          0.0.0.0:*               LISTEN      4461/consul         
    tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      3644/epmd           
    tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      4461/consul         
    tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1110/sshd           
    tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      18055/beam.smp      
    tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      4461/consul         
    tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1776/master         
    tcp        0    212 192.168.32.206:22       10.242.2.6:58218        VERBUNDEN   16467/sshd: root@pt 
    tcp        0      0 127.0.0.1:57143         127.0.0.1:4369          VERBUNDEN   18055/beam.smp      
    tcp        0      0 127.0.0.1:4369          127.0.0.1:57143         VERBUNDEN   3644/epmd           
    tcp        0      0 127.0.0.1:55444         127.0.0.1:8400          TIME_WAIT   -                   
    tcp6       0      0 :::5672                 :::*                    LISTEN      18055/beam.smp      
    tcp6       0      0 :::8301                 :::*                    LISTEN      4461/consul         
    tcp6       0      0 :::22                   :::*                    LISTEN      1110/sshd           
    tcp6       0      0 ::1:25                  :::*                    LISTEN      1776/master

**Comment by gmr** [comment]
The error is that the plugin could not talk to Consul, yet I see consul is running and bound on 127.0.0.1:8500. Is there by chance iptables rules or something blocking?

Can you try running:

``curl -v "http://127.0.0.1:8500/v1/catalog/service/rabbitmq:autocluster?tag=envisia"``

and see if you can connect?

**Comment by gmr** [comment]
0.3.1 has been released and may solve your issue. Please re-open if you're still having issues.
