### ISSUE TITLE
Re-joining cluster fails

### ISSUE THREAD

**Issue by cap10morgan** [aweber/rabbitmq-autocluster-consul#4]
When a node that had been a member of the cluster fails (but does not remove itself from the cluster for whatever reason) and is then brought back up, it cannot successfully re-join the cluster.

Instead I see errors like this:
```
Already member of cluster: ['rabbit@ip-10-36-136-99','rabbit@ip-10-36-126-31','rabbit@ip-10-36-116-78']
```

[Full transcript of startup log](https://gist.github.com/cap10morgan/8cddfde9eca7e2ed657e)

**Comment by gmr** [comment]
Hmm, I can see how that could be problematic. I'll take a look ASAP.

**Comment by gmr** [comment]
The commit I just made should address the issue. I'm going to add in a few more features and release 0.2.0 which should address this issue.

**Comment by cap10morgan** [comment]
Awesome, thanks @gmr!
