### ISSUE TITLE
Service is not discoverable via DNS

### ISSUE THREAD

**Issue by cap10morgan** [aweber/rabbitmq-autocluster-consul#6]
From the Consul logs:

```
Service name "rabbitmq.autocluster" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
```

Looks like it needs to drop the `.`. Can it just be named "rabbitmq"? I'm not sure what value the "autocluster" part is adding.

**Comment by gmr** [comment]
it's keeping auto-clustering service discovering from mingling with any rabbitmq service discovery (on port 5672) one would want to do with consul.

**Comment by cap10morgan** [comment]
Ah, OK. In that case, is there any reason not to register rabbitmq itself (on port 5672) as a service with this plugin?

**Comment by gmr** [comment]
It's too opinionated IMO. We register our clusters with other metadata and service checks. Doing so would cross a line into telling people who use the plugin how they should register RabbitMQ :)

**Comment by gmr** [comment]
Of course, if you want to set it to RabbitMQ and have it use that, it's just fine, with your patch, you add that option, I just don't want it to default to that behavior.

**Comment by cap10morgan** [comment]
I :heart: opinionated software. :)

This plugin already gets 90% of the way to a "It Just Works" Consul-based RabbitMQ cluster. Why not fill in that remaining 10% and make it configurable if people have other needs?

I'm thinking something like this:

By default, this plugin registers services `rabbitmq-autocluster` (current behavior but service name is configurable) and `rabbitmq` (port 5672; sane default service check; name configurable; also possible to disable in configuration if you have more complex needs).

The "sane default service check" could be an HTTP check against `http://node:15672/api/aliveness-test/%2f`.

If you think this is conceptually OK, I'd be happy to make a separate PR for it.

**Comment by gmr** [comment]
I think it's conceptually ok and will merge it as long as it has a enable/disable setting like "register_service" or something...
