### ISSUE TITLE
Can the autocluster part of 'rabbitmq.autocluster' be optional?

### ISSUE THREAD

**Issue by memelet** [aweber/rabbitmq-autocluster-consul#8]
It would be nice to have an option to define a suffix if desired. Otherwise just use what was specified for 'consul_service'.

**Comment by memelet** [comment]
BTW, this worked first time. Very very nice.

**Comment by memelet** [comment]
Maybe I have misunderstood the purpose of the .autocluster. It is expected that I will define separate consul services for each rabbit server separately? Services which have health checks?

**Comment by gmr** [comment]
I believe this is supported in master currently (optional suffix). The point of the suffix is to not make opinionated use of the rabbitmq service namespace in case you want to register it yourself. That being said, there will be a setting in the next version that will setup an opinionated rabbitmq service with health-check and use that for discovery as well.

**Comment by memelet** [comment]
Ah, I did set 'consul_service' property. But 0.2 is not master. Thanks!

**Comment by gmr** [comment]
0.3 is going to drop today or tomorrow that makes this optional.
